
std_msgs/Header header

uint16 group_fields
uint64 timestartup
uint64 timegps
uint64 timesyncin
geometry_msgs/Vector3 ypr
geometry_msgs/Quaternion quaternion
geometry_msgs/Vector3 angularrate
geometry_msgs/Point poslla
geometry_msgs/Vector3 velned
geometry_msgs/Vector3 accel
vectornav_msgs/Imu imu
vectornav_msgs/MagPres magpres
vectornav_msgs/Deltas deltas
vectornav_msgs/InsStatus insstatus
uint32 syncincnt
uint64 timegpspps

