
std_msgs/Header header

uint16 group_fields
vectornav_msgs/TimeUtc gnss2timeutc
uint64 gps2tow
uint16 gps2week
uint8 gnss2numsats
uint8 gnss2fix
geometry_msgs/Point gnss2poslla
geometry_msgs/Point gnss2posecef
geometry_msgs/Vector3 gnss2velned
geometry_msgs/Vector3 gnss2velecef
geometry_msgs/Vector3 gnss2posuncertainty
float32 gnss2veluncertainty
float32 gnss2timeuncertainty
vectornav_msgs/GnssTimeInfo gnss2timeinfo
vectornav_msgs/GnssDop gnss2dop
vectornav_msgs/GnssSatInfo gnss2satinfo
vectornav_msgs/GnssRawMeas gnss2rawmeas
vectornav_msgs/GnssStatus gnss2status
float64 gnss2altmsl

