
std_msgs/Header header

uint16 group_fields
vectornav_msgs/TimeUtc gnss1timeutc
uint64 gps1tow
uint16 gps1week
uint8 gnss1numsats
uint8 gnss1fix
geometry_msgs/Point gnss1poslla
geometry_msgs/Point gnss1posecef
geometry_msgs/Vector3 gnss1velned
geometry_msgs/Vector3 gnss1velecef
geometry_msgs/Vector3 gnss1posuncertainty
float32 gnss1veluncertainty
float32 gnss1timeuncertainty
vectornav_msgs/GnssTimeInfo gnss1timeinfo
vectornav_msgs/GnssDop gnss1dop
vectornav_msgs/GnssSatInfo gnss1satinfo
vectornav_msgs/GnssRawMeas gnss1rawmeas
vectornav_msgs/GnssStatus gnss1status
float64 gnss1altmsl

